apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080  
      protocol: TCP
      nodePort: 30157
  selector:
    app: hello-world
